name: Deployment Terraform

on:
  workflow_run:
    workflows: ["Docker Image Seguridad", "Docker Image Ingestion", "Docker Image BFF", "Docker Image Autorizacion"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
    
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
  
      - name: "Use gcloud CLI"
        run: "gcloud info"
      - name: "Gloud config"
        run: |-
          gcloud config set project nomonoliticas-452502
          gcloud container clusters get-credentials pulsar-dev --zone us-central1-a --project nomonoliticas-452502

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: Initialize Terraform
        run: terraform init

      - name: Deploy infrastructure
        run: terraform plan

      - name: Deploy infrastructure
        run: terraform apply -auto-approve

