name: Deployment Terraform

on:
  workflow_run:
    workflows: ["Docker Image Seguridad", "Docker Image Ingestion"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: Initialize Terraform
        run: terraform init

      - name: Deploy infrastructure
        run: terraform plan

      - name: Deploy infrastructure
        run: terraform apply -auto-approve

