name: Docker Image orquestrador

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: "actions/checkout@v3"
    - id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
    
    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"
    
    - name: "Use gcloud CLI"
      run: "gcloud info"
    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
    - name: Build the Docker image
      run: docker build ./services --file services/orquestrador.Dockerfile --tag us-central1-docker.pkg.dev/nomonoliticas-452502/saludtech/orquestrador
    - name: Push the Docker image
      run: docker push us-central1-docker.pkg.dev/nomonoliticas-452502/saludtech/orquestrador
